name: Mi primer Pipeline

on:
  # Ejecutar cada que se realice un push
  push:
    branches:
    - main
    - release/*

  pull_request:
    types: [opened, synchronize, reopened, review_request]
    branches:
    - main

  # Ejecutar de manera programada
  schedule:
  - cron: "0 2 * * 1-5"

    #Permitir ejecutar manualmente
  workflow_dispatch:

jobs:
  correr_tests:
   runs-on: ubuntu-latest

   steps:
     - name: Realizamos un checkout a la ram
       uses: actions/checkout@v2

     - name: Usamos Nodejs 20.X
       uses: actions/setup-node@V4
       with:
         node-version: '20.x'
         cache: 'npm'

     - name: Instalar dependencias
       run: |
        npm install
        npm run build --if-present

    # - name: Corremos el linter
    #  run: npm run lint

     - name: Corremos las pruebas unitarias y de integracion con su covertura
       run: npm run test:cov
       
     - name: Corremos las pruebas e2e
       run: npm run test:e2e

     - name: Actualizamos el artefacto con el reporte de covertura de los test
       uses: actions/upload-artifact@V4
       with:
         name: coverage-report
         path: coverage/
         retention-days: 7
         if-no-files-found: error


        




    
