name: Mi primer Pipeline

on:
  # Ejecutar cada que se realice un push
  push:
    branches:
    - main
    - release/*

  pull_request:
    types: [opened, synchronize, reopened, review_request]
    branches:
    - main

  # Ejecutar de manera programada
  schedule:
  - cron: "0 2 * * 1-5"

    #Permitir ejecutar manualmente
  workflow_dispatch:

jobs:
  correr_tests:
   runs-on: ubuntu-latest

   steps:
     - name: Realizamos un checkout a la ram
       uses: actions/checkout@v2

     - name: Usamos Nodejs 20.X
       uses: actions/setup-node@V4
       with:
         node-version: '20.x'
         cache: 'npm'

     - name: Instalar dependencias
       run: |
        npm install
        npm run build --if-present


        




    
